### ISSUE TITLE
Create shop menu/upgrades

### ISSUE THREAD

**Issue by Chissanu** [Chissanu/UWU-Re#8]
Ton's Task
- Design what type of upgrades/buff/items to be included in a shop
- Consider using queue for buffs (50 Seconds until buff expires)

Ruj's Task
- Design shop sprite/UI
- Implement code to instead of random between (1-4) with 25% chance of spawning platform with monster to have 10% chance to spawn with shop

**Comment by Tonkhaowm8** [comment]
only 5 seconds is enough, 50 seconds is too long for me *wink*

**Comment by Tonkhaowm8** [comment]
finish
